#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventPlannerCR_AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EventPlanner")]
	public partial class ConexionLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ConexionLinqDataContext() : 
				base(global::EventPlannerCR_AccesoDatos.Properties.Settings.Default.EventPlannerConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Actualizar_Clima")]
		public int SP_Actualizar_Clima([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDEVENTO", DbType="Int")] System.Nullable<int> iDEVENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLIMA", DbType="NVarChar(MAX)")] string cLIMA, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idBD, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idError, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDEVENTO, cLIMA, idBD, idError, errorDescripcion);
			idBD = ((System.Nullable<int>)(result.GetParameterValue(2)));
			idError = ((System.Nullable<int>)(result.GetParameterValue(3)));
			errorDescripcion = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarUsuario")]
		public int SP_InsertarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellidos", DbType="NVarChar(100)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="NVarChar(15)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="NVarChar(100)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaNacimiento", DbType="Date")] System.Nullable<System.DateTime> fechaNacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Admin", DbType="Bit")] System.Nullable<bool> admin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(255)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Vehiculo", DbType="Bit")] System.Nullable<bool> vehiculo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, apellidos, telefono, correo, fechaNacimiento, admin, password, vehiculo, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(8)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(9)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(10)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_BorrarAsistencia")]
		public int SP_BorrarAsistencia([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdAsistencia", DbType="Int")] System.Nullable<int> idAsistencia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idError, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idAsistencia, idError, errorDescripcion);
			idError = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorDescripcion = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_BuscarAsistenciaPorEvento")]
		public ISingleResult<SP_BuscarAsistenciaPorEventoResult> SP_BuscarAsistenciaPorEvento([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEvento", DbType="Int")] System.Nullable<int> idEvento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idError, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEvento, idError, errorDescripcion);
			idError = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorDescripcion = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_BuscarAsistenciaPorEventoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_BuscarAsistenciaPorUsuario")]
		public ISingleResult<SP_BuscarAsistenciaPorUsuarioResult> SP_BuscarAsistenciaPorUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idError, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, idError, errorDescripcion);
			idError = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorDescripcion = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_BuscarAsistenciaPorUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_BuscarCanton")]
		public ISingleResult<SP_BuscarCantonResult> SP_BuscarCanton([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROVINCIA", DbType="NVarChar(50)")] string pROVINCIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] ref System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pROVINCIA, iD);
			iD = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((ISingleResult<SP_BuscarCantonResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_BuscarCarpoolPorEvento2")]
		public ISingleResult<SP_BuscarCarpoolPorEvento2Result> SP_BuscarCarpoolPorEvento2([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEvento", DbType="Int")] System.Nullable<int> idEvento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEvento, eRRORID, eRRORDESCRIPCION);
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_BuscarCarpoolPorEvento2Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_BuscarCarpoolPorUsuario2")]
		public ISingleResult<SP_BuscarCarpoolPorUsuario2Result> SP_BuscarCarpoolPorUsuario2([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, eRRORID, eRRORDESCRIPCION);
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_BuscarCarpoolPorUsuario2Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_BuscarDistrito")]
		public ISingleResult<SP_BuscarDistritoResult> SP_BuscarDistrito([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CANTON", DbType="NVarChar(50)")] string cANTON, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] ref System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cANTON, iD);
			iD = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((ISingleResult<SP_BuscarDistritoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_BuscarProvincia")]
		public ISingleResult<SP_BuscarProvinciaResult> SP_BuscarProvincia([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROVINCIA", DbType="NVarChar(50)")] string pROVINCIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] ref System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pROVINCIA, iD);
			iD = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((ISingleResult<SP_BuscarProvinciaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_BuscarUsuariosPorCarpool")]
		public ISingleResult<SP_BuscarUsuariosPorCarpoolResult> SP_BuscarUsuariosPorCarpool([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCarpool", DbType="Int")] System.Nullable<int> idCarpool, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCarpool, eRRORID, eRRORDESCRIPCION);
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_BuscarUsuariosPorCarpoolResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EditarAsistencia")]
		public ISingleResult<SP_EditarAsistenciaResult> SP_EditarAsistencia([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdAsistencia", DbType="Int")] System.Nullable<int> idAsistencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Bit")] System.Nullable<bool> status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCarpool", DbType="Int")] System.Nullable<int> idCarpool, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idError, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idAsistencia, status, idCarpool, idError, errorDescripcion);
			idError = ((System.Nullable<int>)(result.GetParameterValue(3)));
			errorDescripcion = ((string)(result.GetParameterValue(4)));
			return ((ISingleResult<SP_EditarAsistenciaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EditarCarpool")]
		public int SP_EditarCarpool([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idEvento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuarioOcupante, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NotasCarpool", DbType="NVarChar(MAX)")] string notasCarpool, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Provincia", DbType="Int")] System.Nullable<int> provincia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Canton", DbType="Int")] System.Nullable<int> canton, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Distrito", DbType="Int")] System.Nullable<int> distrito, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoraSalida", DbType="DateTime")] System.Nullable<System.DateTime> horaSalida, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCarpool_Nuevo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorID", DbType="Int")] ref System.Nullable<int> errorID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorDescripcion", DbType="NVarChar(MAX)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, idEvento, idUsuarioOcupante, notasCarpool, provincia, canton, distrito, horaSalida, idCarpool_Nuevo, errorID, errorDescripcion);
			errorID = ((System.Nullable<int>)(result.GetParameterValue(9)));
			errorDescripcion = ((string)(result.GetParameterValue(10)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EventosCercanos")]
		public ISingleResult<SP_EventosCercanosResult> SP_EventosCercanos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_EventosCercanosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarAsistencia")]
		public int SP_InsertarAsistencia([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEvento", DbType="Int")] System.Nullable<int> idEvento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Bit")] System.Nullable<bool> status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FkCarpool", DbType="Int")] System.Nullable<int> fkCarpool, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, idEvento, status, fkCarpool, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarBitacora")]
		public int SP_InsertarBitacora([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Clase", DbType="NVarChar(100)")] string clase, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Metodo", DbType="NVarChar(100)")] string metodo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="NVarChar(100)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Error_ID", DbType="NVarChar(50)")] string error_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="NVarChar(MAX)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Request", DbType="NVarChar(MAX)")] string request, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Response", DbType="NVarChar(MAX)")] string response, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idBD, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idError, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clase, metodo, tipo, error_ID, descripcion, request, response, idBD, idError, errorDescripcion);
			idBD = ((System.Nullable<int>)(result.GetParameterValue(7)));
			idError = ((System.Nullable<int>)(result.GetParameterValue(8)));
			errorDescripcion = ((string)(result.GetParameterValue(9)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarCarpool")]
		public int SP_InsertarCarpool([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEvento", DbType="Int")] System.Nullable<int> idEvento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CamposDisponibles", DbType="Int")] System.Nullable<int> camposDisponibles, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Provincia", DbType="Int")] System.Nullable<int> provincia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Canton", DbType="Int")] System.Nullable<int> canton, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Distrito", DbType="Int")] System.Nullable<int> distrito, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NotasCarpool", DbType="VarChar(MAX)")] string notasCarpool, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEvento, camposDisponibles, provincia, canton, distrito, idUsuario, notasCarpool, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(7)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(8)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(9)));
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class SP_BuscarAsistenciaPorEventoResult
	{
		
		private int _IdAsistencia;
		
		private string _NombreCompleto;
		
		private string _NombreEvento;
		
		private string _DescripcionEvento;
		
		private System.DateTime _FechaEvento;
		
		private string _LugarEvento;
		
		private string _Transporte;
		
		private string _Estado;
		
		private System.DateTime _ConfirmacionAsistencia;
		
		public SP_BuscarAsistenciaPorEventoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAsistencia", DbType="Int NOT NULL")]
		public int IdAsistencia
		{
			get
			{
				return this._IdAsistencia;
			}
			set
			{
				if ((this._IdAsistencia != value))
				{
					this._IdAsistencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCompleto", DbType="NVarChar(201) NOT NULL", CanBeNull=false)]
		public string NombreCompleto
		{
			get
			{
				return this._NombreCompleto;
			}
			set
			{
				if ((this._NombreCompleto != value))
				{
					this._NombreCompleto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreEvento", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreEvento
		{
			get
			{
				return this._NombreEvento;
			}
			set
			{
				if ((this._NombreEvento != value))
				{
					this._NombreEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionEvento", DbType="NVarChar(MAX)")]
		public string DescripcionEvento
		{
			get
			{
				return this._DescripcionEvento;
			}
			set
			{
				if ((this._DescripcionEvento != value))
				{
					this._DescripcionEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEvento", DbType="DateTime NOT NULL")]
		public System.DateTime FechaEvento
		{
			get
			{
				return this._FechaEvento;
			}
			set
			{
				if ((this._FechaEvento != value))
				{
					this._FechaEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LugarEvento", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string LugarEvento
		{
			get
			{
				return this._LugarEvento;
			}
			set
			{
				if ((this._LugarEvento != value))
				{
					this._LugarEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transporte", DbType="NVarChar(111)")]
		public string Transporte
		{
			get
			{
				return this._Transporte;
			}
			set
			{
				if ((this._Transporte != value))
				{
					this._Transporte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmacionAsistencia", DbType="DateTime NOT NULL")]
		public System.DateTime ConfirmacionAsistencia
		{
			get
			{
				return this._ConfirmacionAsistencia;
			}
			set
			{
				if ((this._ConfirmacionAsistencia != value))
				{
					this._ConfirmacionAsistencia = value;
				}
			}
		}
	}
	
	public partial class SP_BuscarAsistenciaPorUsuarioResult
	{
		
		private int _IdAsistencia;
		
		private string _NombreCompleto;
		
		private string _NombreEvento;
		
		private string _DescripcionEvento;
		
		private System.DateTime _FechaEvento;
		
		private string _LugarEvento;
		
		private string _Transporte;
		
		private string _Estado;
		
		private System.DateTime _ConfirmacionAsistencia;
		
		public SP_BuscarAsistenciaPorUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAsistencia", DbType="Int NOT NULL")]
		public int IdAsistencia
		{
			get
			{
				return this._IdAsistencia;
			}
			set
			{
				if ((this._IdAsistencia != value))
				{
					this._IdAsistencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCompleto", DbType="NVarChar(201) NOT NULL", CanBeNull=false)]
		public string NombreCompleto
		{
			get
			{
				return this._NombreCompleto;
			}
			set
			{
				if ((this._NombreCompleto != value))
				{
					this._NombreCompleto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreEvento", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreEvento
		{
			get
			{
				return this._NombreEvento;
			}
			set
			{
				if ((this._NombreEvento != value))
				{
					this._NombreEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionEvento", DbType="NVarChar(MAX)")]
		public string DescripcionEvento
		{
			get
			{
				return this._DescripcionEvento;
			}
			set
			{
				if ((this._DescripcionEvento != value))
				{
					this._DescripcionEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEvento", DbType="DateTime NOT NULL")]
		public System.DateTime FechaEvento
		{
			get
			{
				return this._FechaEvento;
			}
			set
			{
				if ((this._FechaEvento != value))
				{
					this._FechaEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LugarEvento", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string LugarEvento
		{
			get
			{
				return this._LugarEvento;
			}
			set
			{
				if ((this._LugarEvento != value))
				{
					this._LugarEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transporte", DbType="NVarChar(111)")]
		public string Transporte
		{
			get
			{
				return this._Transporte;
			}
			set
			{
				if ((this._Transporte != value))
				{
					this._Transporte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmacionAsistencia", DbType="DateTime NOT NULL")]
		public System.DateTime ConfirmacionAsistencia
		{
			get
			{
				return this._ConfirmacionAsistencia;
			}
			set
			{
				if ((this._ConfirmacionAsistencia != value))
				{
					this._ConfirmacionAsistencia = value;
				}
			}
		}
	}
	
	public partial class SP_BuscarCantonResult
	{
		
		private int _Id;
		
		private string _Nombre;
		
		public SP_BuscarCantonResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	public partial class SP_BuscarCarpoolPorEvento2Result
	{
		
		private int _IdCarpool;
		
		private string _NombreCompletoDueno;
		
		private string _CamposDisponibles;
		
		private string _NombreEvento;
		
		private string _DireccionOrigen;
		
		private string _DireccionDestino;
		
		private System.DateTime _HoraSalida;
		
		private string _NotasCarpool;
		
		public SP_BuscarCarpoolPorEvento2Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCarpool", DbType="Int NOT NULL")]
		public int IdCarpool
		{
			get
			{
				return this._IdCarpool;
			}
			set
			{
				if ((this._IdCarpool != value))
				{
					this._IdCarpool = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCompletoDueno", DbType="NVarChar(201) NOT NULL", CanBeNull=false)]
		public string NombreCompletoDueno
		{
			get
			{
				return this._NombreCompletoDueno;
			}
			set
			{
				if ((this._NombreCompletoDueno != value))
				{
					this._NombreCompletoDueno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CamposDisponibles", DbType="VarChar(61)")]
		public string CamposDisponibles
		{
			get
			{
				return this._CamposDisponibles;
			}
			set
			{
				if ((this._CamposDisponibles != value))
				{
					this._CamposDisponibles = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreEvento", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreEvento
		{
			get
			{
				return this._NombreEvento;
			}
			set
			{
				if ((this._NombreEvento != value))
				{
					this._NombreEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DireccionOrigen", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DireccionOrigen
		{
			get
			{
				return this._DireccionOrigen;
			}
			set
			{
				if ((this._DireccionOrigen != value))
				{
					this._DireccionOrigen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DireccionDestino", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DireccionDestino
		{
			get
			{
				return this._DireccionDestino;
			}
			set
			{
				if ((this._DireccionDestino != value))
				{
					this._DireccionDestino = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraSalida", DbType="DateTime NOT NULL")]
		public System.DateTime HoraSalida
		{
			get
			{
				return this._HoraSalida;
			}
			set
			{
				if ((this._HoraSalida != value))
				{
					this._HoraSalida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotasCarpool", DbType="VarChar(MAX)")]
		public string NotasCarpool
		{
			get
			{
				return this._NotasCarpool;
			}
			set
			{
				if ((this._NotasCarpool != value))
				{
					this._NotasCarpool = value;
				}
			}
		}
	}
	
	public partial class SP_BuscarCarpoolPorUsuario2Result
	{
		
		private int _IdCarpool;
		
		private int _IdEvento;
		
		private string _NombreEvento;
		
		private int _CamposDisponibles;
		
		private string _DireccionOrigen;
		
		private string _DireccionDestino;
		
		private System.DateTime _HoraSalida;
		
		private string _NotasCarpool;
		
		private System.Nullable<int> _CamposRestantes;
		
		private string _NombreCompletoDueno;
		
		private string _CarpoolUsuarios;
		
		public SP_BuscarCarpoolPorUsuario2Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCarpool", DbType="Int NOT NULL")]
		public int IdCarpool
		{
			get
			{
				return this._IdCarpool;
			}
			set
			{
				if ((this._IdCarpool != value))
				{
					this._IdCarpool = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEvento", DbType="Int NOT NULL")]
		public int IdEvento
		{
			get
			{
				return this._IdEvento;
			}
			set
			{
				if ((this._IdEvento != value))
				{
					this._IdEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreEvento", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreEvento
		{
			get
			{
				return this._NombreEvento;
			}
			set
			{
				if ((this._NombreEvento != value))
				{
					this._NombreEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CamposDisponibles", DbType="Int NOT NULL")]
		public int CamposDisponibles
		{
			get
			{
				return this._CamposDisponibles;
			}
			set
			{
				if ((this._CamposDisponibles != value))
				{
					this._CamposDisponibles = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DireccionOrigen", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DireccionOrigen
		{
			get
			{
				return this._DireccionOrigen;
			}
			set
			{
				if ((this._DireccionOrigen != value))
				{
					this._DireccionOrigen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DireccionDestino", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DireccionDestino
		{
			get
			{
				return this._DireccionDestino;
			}
			set
			{
				if ((this._DireccionDestino != value))
				{
					this._DireccionDestino = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraSalida", DbType="DateTime NOT NULL")]
		public System.DateTime HoraSalida
		{
			get
			{
				return this._HoraSalida;
			}
			set
			{
				if ((this._HoraSalida != value))
				{
					this._HoraSalida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotasCarpool", DbType="VarChar(MAX)")]
		public string NotasCarpool
		{
			get
			{
				return this._NotasCarpool;
			}
			set
			{
				if ((this._NotasCarpool != value))
				{
					this._NotasCarpool = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CamposRestantes", DbType="Int")]
		public System.Nullable<int> CamposRestantes
		{
			get
			{
				return this._CamposRestantes;
			}
			set
			{
				if ((this._CamposRestantes != value))
				{
					this._CamposRestantes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCompletoDueno", DbType="NVarChar(201) NOT NULL", CanBeNull=false)]
		public string NombreCompletoDueno
		{
			get
			{
				return this._NombreCompletoDueno;
			}
			set
			{
				if ((this._NombreCompletoDueno != value))
				{
					this._NombreCompletoDueno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarpoolUsuarios", DbType="NVarChar(MAX)")]
		public string CarpoolUsuarios
		{
			get
			{
				return this._CarpoolUsuarios;
			}
			set
			{
				if ((this._CarpoolUsuarios != value))
				{
					this._CarpoolUsuarios = value;
				}
			}
		}
	}
	
	public partial class SP_BuscarDistritoResult
	{
		
		private int _Id;
		
		private string _Nombre;
		
		public SP_BuscarDistritoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	public partial class SP_BuscarProvinciaResult
	{
		
		private int _Id;
		
		private string _Nombre;
		
		public SP_BuscarProvinciaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	public partial class SP_BuscarUsuariosPorCarpoolResult
	{
		
		private int _ID_USUARIO;
		
		private string _NombreApellido;
		
		public SP_BuscarUsuariosPorCarpoolResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int NOT NULL")]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this._ID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreApellido", DbType="NVarChar(201) NOT NULL", CanBeNull=false)]
		public string NombreApellido
		{
			get
			{
				return this._NombreApellido;
			}
			set
			{
				if ((this._NombreApellido != value))
				{
					this._NombreApellido = value;
				}
			}
		}
	}
	
	public partial class SP_EditarAsistenciaResult
	{
		
		private int _IdAsistencia;
		
		private string _NombreCompleto;
		
		private string _NombreEvento;
		
		private string _DescripcionEvento;
		
		private System.DateTime _FechaEvento;
		
		private string _LugarEvento;
		
		private string _Transporte;
		
		private string _Estado;
		
		private System.DateTime _ConfirmacionAsistencia;
		
		public SP_EditarAsistenciaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAsistencia", DbType="Int NOT NULL")]
		public int IdAsistencia
		{
			get
			{
				return this._IdAsistencia;
			}
			set
			{
				if ((this._IdAsistencia != value))
				{
					this._IdAsistencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCompleto", DbType="NVarChar(201) NOT NULL", CanBeNull=false)]
		public string NombreCompleto
		{
			get
			{
				return this._NombreCompleto;
			}
			set
			{
				if ((this._NombreCompleto != value))
				{
					this._NombreCompleto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreEvento", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreEvento
		{
			get
			{
				return this._NombreEvento;
			}
			set
			{
				if ((this._NombreEvento != value))
				{
					this._NombreEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionEvento", DbType="NVarChar(MAX)")]
		public string DescripcionEvento
		{
			get
			{
				return this._DescripcionEvento;
			}
			set
			{
				if ((this._DescripcionEvento != value))
				{
					this._DescripcionEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEvento", DbType="DateTime NOT NULL")]
		public System.DateTime FechaEvento
		{
			get
			{
				return this._FechaEvento;
			}
			set
			{
				if ((this._FechaEvento != value))
				{
					this._FechaEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LugarEvento", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string LugarEvento
		{
			get
			{
				return this._LugarEvento;
			}
			set
			{
				if ((this._LugarEvento != value))
				{
					this._LugarEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transporte", DbType="NVarChar(111)")]
		public string Transporte
		{
			get
			{
				return this._Transporte;
			}
			set
			{
				if ((this._Transporte != value))
				{
					this._Transporte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmacionAsistencia", DbType="DateTime NOT NULL")]
		public System.DateTime ConfirmacionAsistencia
		{
			get
			{
				return this._ConfirmacionAsistencia;
			}
			set
			{
				if ((this._ConfirmacionAsistencia != value))
				{
					this._ConfirmacionAsistencia = value;
				}
			}
		}
	}
	
	public partial class SP_EventosCercanosResult
	{
		
		private int _IdEvento;
		
		private System.Nullable<System.DateTime> _FechaInicio;
		
		private System.Nullable<decimal> _lat;
		
		private System.Nullable<decimal> _lon;
		
		private System.Nullable<int> _DiasParaEvento;
		
		public SP_EventosCercanosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEvento", DbType="Int NOT NULL")]
		public int IdEvento
		{
			get
			{
				return this._IdEvento;
			}
			set
			{
				if ((this._IdEvento != value))
				{
					this._IdEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaInicio", DbType="Date")]
		public System.Nullable<System.DateTime> FechaInicio
		{
			get
			{
				return this._FechaInicio;
			}
			set
			{
				if ((this._FechaInicio != value))
				{
					this._FechaInicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lat", DbType="Decimal(9,6)")]
		public double lat
		{
			get
			{
				return (double)this._lat;
			}
			set
			{
				if ((this._lat != (decimal?)value))
				{
					this._lat = (decimal?)value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lon", DbType="Decimal(9,6)")]
		public double lon
		{
			get
			{
				return (double)this._lon;
			}
			set
			{
				if ((this._lon != (decimal?)value))
				{
					this._lon = (decimal?)value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiasParaEvento", DbType="Int")]
		public int DiasParaEvento
		{
			get
			{
				return (int)this._DiasParaEvento;
			}
			set
			{
				if ((this._DiasParaEvento != value))
				{
					this._DiasParaEvento = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
