#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventPlannerCR_AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EventPlanner")]
	public partial class ConexionLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ConexionLinqDataContext() : 
				base(global::EventPlannerCR_AccesoDatos.Properties.Settings.Default.EventPlannerConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarUsuario")]
		public int SP_InsertarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellidos", DbType="NVarChar(100)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="NVarChar(15)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="NVarChar(100)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaNacimiento", DbType="Date")] System.Nullable<System.DateTime> fechaNacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Provincia", DbType="NVarChar(100)")] string provincia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Admin", DbType="Bit")] System.Nullable<bool> admin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(255)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Vehiculo", DbType="Bit")] System.Nullable<bool> vehiculo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, apellidos, telefono, correo, fechaNacimiento, provincia, admin, password, vehiculo, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(9)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(10)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(11)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarBitacora")]
		public int SP_InsertarBitacora([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Clase", DbType="NVarChar(100)")] string clase, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Metodo", DbType="NVarChar(100)")] string metodo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="NVarChar(100)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Error_ID", DbType="NVarChar(50)")] string error_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="NVarChar(MAX)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Request", DbType="NVarChar(MAX)")] string request, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Response", DbType="NVarChar(MAX)")] string response, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idBD, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idError, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clase, metodo, tipo, error_ID, descripcion, request, response, idBD, idError, errorDescripcion);
			idBD = ((System.Nullable<int>)(result.GetParameterValue(7)));
			idError = ((System.Nullable<int>)(result.GetParameterValue(8)));
			errorDescripcion = ((string)(result.GetParameterValue(9)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EventosCercanos")]
		public ISingleResult<SP_EventosCercanosResult> SP_EventosCercanos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_EventosCercanosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_BuscarCarpoolPorEvento")]
		public ISingleResult<SP_BuscarCarpoolPorEventoResult> SP_BuscarCarpoolPorEvento([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEvento", DbType="Int")] System.Nullable<int> idEvento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEvento, eRRORID, eRRORDESCRIPCION);
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_BuscarCarpoolPorEventoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarCarpool")]
		public int SP_InsertarCarpool([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEvento", DbType="Int")] System.Nullable<int> idEvento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CamposDisponibles", DbType="Int")] System.Nullable<int> camposDisponibles, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Provincia", DbType="Int")] System.Nullable<int> provincia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Canton", DbType="Int")] System.Nullable<int> canton, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Distrito", DbType="Int")] System.Nullable<int> distrito, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEvento, camposDisponibles, provincia, canton, distrito, idUsuario, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(7)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarAsistencia")]
		public int SP_InsertarAsistencia([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEvento", DbType="Int")] System.Nullable<int> idEvento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Bit")] System.Nullable<bool> status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FkCarpool", DbType="Int")] System.Nullable<int> fkCarpool, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, idEvento, status, fkCarpool, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_BuscarAsistenciaPorEvento")]
		public ISingleResult<SP_BuscarAsistenciaPorEventoResult> SP_BuscarAsistenciaPorEvento([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEvento", DbType="Int")] System.Nullable<int> idEvento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idError, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEvento, idError, errorDescripcion);
			idError = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorDescripcion = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_BuscarAsistenciaPorEventoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_BuscarAsistenciaPorUsuario")]
		public ISingleResult<SP_BuscarAsistenciaPorUsuarioResult> SP_BuscarAsistenciaPorUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idError, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, idError, errorDescripcion);
			idError = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorDescripcion = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_BuscarAsistenciaPorUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EditarAsistencia")]
		public ISingleResult<SP_EditarAsistenciaResult> SP_EditarAsistencia([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdAsistencia", DbType="Int")] System.Nullable<int> idAsistencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Bit")] System.Nullable<bool> status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCarpool", DbType="Int")] System.Nullable<int> idCarpool, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idError, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idAsistencia, status, idCarpool, idError, errorDescripcion);
			idError = ((System.Nullable<int>)(result.GetParameterValue(3)));
			errorDescripcion = ((string)(result.GetParameterValue(4)));
			return ((ISingleResult<SP_EditarAsistenciaResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_EventosCercanosResult
	{
		
		private int _IdEvento;
		
		private System.DateTime _FechaInicio;
		
		private System.Nullable<decimal> _lat;
		
		private System.Nullable<decimal> _lon;
		
		private System.Nullable<int> _DiasParaEvento;
		
		public SP_EventosCercanosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEvento", DbType="Int NOT NULL")]
		public int IdEvento
		{
			get
			{
				return this._IdEvento;
			}
			set
			{
				if ((this._IdEvento != value))
				{
					this._IdEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaInicio", DbType="DateTime NOT NULL")]
		public System.DateTime FechaInicio
		{
			get
			{
				return this._FechaInicio;
			}
			set
			{
				if ((this._FechaInicio != value))
				{
					this._FechaInicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lat", DbType="Decimal(9,6)")]
		public System.Nullable<decimal> lat
		{
			get
			{
				return this._lat;
			}
			set
			{
				if ((this._lat != value))
				{
					this._lat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lon", DbType="Decimal(9,6)")]
		public System.Nullable<decimal> lon
		{
			get
			{
				return this._lon;
			}
			set
			{
				if ((this._lon != value))
				{
					this._lon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiasParaEvento", DbType="Int")]
		public System.Nullable<int> DiasParaEvento
		{
			get
			{
				return this._DiasParaEvento;
			}
			set
			{
				if ((this._DiasParaEvento != value))
				{
					this._DiasParaEvento = value;
				}
			}
		}
	}
	
	public partial class SP_BuscarCarpoolPorEventoResult
	{
		
		private int _IdCarpool;
		
		private int _IdEvento;
		
		private int _CamposDisponibles;
		
		private int _Provincia;
		
		private int _Canton;
		
		private int _Distrito;
		
		public SP_BuscarCarpoolPorEventoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCarpool", DbType="Int NOT NULL")]
		public int IdCarpool
		{
			get
			{
				return this._IdCarpool;
			}
			set
			{
				if ((this._IdCarpool != value))
				{
					this._IdCarpool = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEvento", DbType="Int NOT NULL")]
		public int IdEvento
		{
			get
			{
				return this._IdEvento;
			}
			set
			{
				if ((this._IdEvento != value))
				{
					this._IdEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CamposDisponibles", DbType="Int NOT NULL")]
		public int CamposDisponibles
		{
			get
			{
				return this._CamposDisponibles;
			}
			set
			{
				if ((this._CamposDisponibles != value))
				{
					this._CamposDisponibles = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provincia", DbType="Int NOT NULL")]
		public int Provincia
		{
			get
			{
				return this._Provincia;
			}
			set
			{
				if ((this._Provincia != value))
				{
					this._Provincia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Canton", DbType="Int NOT NULL")]
		public int Canton
		{
			get
			{
				return this._Canton;
			}
			set
			{
				if ((this._Canton != value))
				{
					this._Canton = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distrito", DbType="Int NOT NULL")]
		public int Distrito
		{
			get
			{
				return this._Distrito;
			}
			set
			{
				if ((this._Distrito != value))
				{
					this._Distrito = value;
				}
			}
		}
	}
	
	public partial class SP_BuscarAsistenciaPorEventoResult
	{
		
		private int _IdAsistencia;
		
		private string _Usuario;
		
		private string _Transporte;
		
		private System.Nullable<System.DateTime> _FechaDeConfirmacion;
		
		private string _Estado;
		
		public SP_BuscarAsistenciaPorEventoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAsistencia", DbType="Int NOT NULL")]
		public int IdAsistencia
		{
			get
			{
				return this._IdAsistencia;
			}
			set
			{
				if ((this._IdAsistencia != value))
				{
					this._IdAsistencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="NVarChar(201) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transporte", DbType="NVarChar(111)")]
		public string Transporte
		{
			get
			{
				return this._Transporte;
			}
			set
			{
				if ((this._Transporte != value))
				{
					this._Transporte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaDeConfirmacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaDeConfirmacion
		{
			get
			{
				return this._FechaDeConfirmacion;
			}
			set
			{
				if ((this._FechaDeConfirmacion != value))
				{
					this._FechaDeConfirmacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class SP_BuscarAsistenciaPorUsuarioResult
	{
		
		private int _IdAsistencia;
		
		private string _NombreCompleto;
		
		private string _NombreEvento;
		
		private string _DescripcionEvento;
		
		private System.DateTime _FechaEvento;
		
		private string _LugarEvento;
		
		private string _Transporte;
		
		private string _Estado;
		
		private System.DateTime _ConfirmacionAsistencia;
		
		public SP_BuscarAsistenciaPorUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAsistencia", DbType="Int NOT NULL")]
		public int IdAsistencia
		{
			get
			{
				return this._IdAsistencia;
			}
			set
			{
				if ((this._IdAsistencia != value))
				{
					this._IdAsistencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCompleto", DbType="NVarChar(201) NOT NULL", CanBeNull=false)]
		public string NombreCompleto
		{
			get
			{
				return this._NombreCompleto;
			}
			set
			{
				if ((this._NombreCompleto != value))
				{
					this._NombreCompleto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreEvento", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreEvento
		{
			get
			{
				return this._NombreEvento;
			}
			set
			{
				if ((this._NombreEvento != value))
				{
					this._NombreEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionEvento", DbType="NVarChar(MAX)")]
		public string DescripcionEvento
		{
			get
			{
				return this._DescripcionEvento;
			}
			set
			{
				if ((this._DescripcionEvento != value))
				{
					this._DescripcionEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEvento", DbType="DateTime NOT NULL")]
		public System.DateTime FechaEvento
		{
			get
			{
				return this._FechaEvento;
			}
			set
			{
				if ((this._FechaEvento != value))
				{
					this._FechaEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LugarEvento", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string LugarEvento
		{
			get
			{
				return this._LugarEvento;
			}
			set
			{
				if ((this._LugarEvento != value))
				{
					this._LugarEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transporte", DbType="NVarChar(111)")]
		public string Transporte
		{
			get
			{
				return this._Transporte;
			}
			set
			{
				if ((this._Transporte != value))
				{
					this._Transporte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmacionAsistencia", DbType="DateTime NOT NULL")]
		public System.DateTime ConfirmacionAsistencia
		{
			get
			{
				return this._ConfirmacionAsistencia;
			}
			set
			{
				if ((this._ConfirmacionAsistencia != value))
				{
					this._ConfirmacionAsistencia = value;
				}
			}
		}
	}
	
	public partial class SP_EditarAsistenciaResult
	{
		
		private int _IdAsistencia;
		
		private string _NombreCompleto;
		
		private string _NombreEvento;
		
		private string _DescripcionEvento;
		
		private System.DateTime _FechaEvento;
		
		private string _LugarEvento;
		
		private string _Transporte;
		
		private string _Estado;
		
		private System.DateTime _ConfirmacionAsistencia;
		
		public SP_EditarAsistenciaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAsistencia", DbType="Int NOT NULL")]
		public int IdAsistencia
		{
			get
			{
				return this._IdAsistencia;
			}
			set
			{
				if ((this._IdAsistencia != value))
				{
					this._IdAsistencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCompleto", DbType="NVarChar(201) NOT NULL", CanBeNull=false)]
		public string NombreCompleto
		{
			get
			{
				return this._NombreCompleto;
			}
			set
			{
				if ((this._NombreCompleto != value))
				{
					this._NombreCompleto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreEvento", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreEvento
		{
			get
			{
				return this._NombreEvento;
			}
			set
			{
				if ((this._NombreEvento != value))
				{
					this._NombreEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionEvento", DbType="NVarChar(MAX)")]
		public string DescripcionEvento
		{
			get
			{
				return this._DescripcionEvento;
			}
			set
			{
				if ((this._DescripcionEvento != value))
				{
					this._DescripcionEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEvento", DbType="DateTime NOT NULL")]
		public System.DateTime FechaEvento
		{
			get
			{
				return this._FechaEvento;
			}
			set
			{
				if ((this._FechaEvento != value))
				{
					this._FechaEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LugarEvento", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string LugarEvento
		{
			get
			{
				return this._LugarEvento;
			}
			set
			{
				if ((this._LugarEvento != value))
				{
					this._LugarEvento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transporte", DbType="NVarChar(111)")]
		public string Transporte
		{
			get
			{
				return this._Transporte;
			}
			set
			{
				if ((this._Transporte != value))
				{
					this._Transporte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmacionAsistencia", DbType="DateTime NOT NULL")]
		public System.DateTime ConfirmacionAsistencia
		{
			get
			{
				return this._ConfirmacionAsistencia;
			}
			set
			{
				if ((this._ConfirmacionAsistencia != value))
				{
					this._ConfirmacionAsistencia = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
